config/routes.rb
Rails.application.routes.draw do

    namespace :api do
      #v1
      match '/v1/cpv' => 'v1#cpv', via: [:get], defaults: { format: 'json' }
      match '/v1/children' => 'v1#children', via: [:get], defaults: { format: 'json' }
      match '/v1/search' => 'v1#search', via: [:get], defaults: { format: 'json' }

    end

    match '/download' => 'root#download', via: [:get]

    root :to => 'root#index'
    match "*path", to: redirect("/"), via: [:get, :post] # handles /fake/path/whatever

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cpv.rb
class Cpv < ApplicationRecord
  has_ancestry

  ##################
  ## VALIDATIONS
  ##################
  validates_presence_of :code, :original_code, :description
  validates :code, length: {is: 8}
  validates :original_code, length: {is: 10}

  ##################
  ## SCOPES
  ##################
  def self.sorted
    order(description: :asc)
  end

  def self.parent_codes
    where('ancestry is null').sorted
  end

  def self.search(q=nil)
    if q.nil?
      Cpv.none
    else
      where(["code ilike ? or description ilike ?", "#{q}%", "%#{q}%"])
    end
  end
end

app/controllers/api/v1_controller.rb
class Api::V1Controller < ApplicationController

  # GET /api/v1/cpv
  # params: code
  def cpv
    item = Cpv.where(code: params[:code]).first

    if item.present?
      render json: {
        'cpv': CpvSerializer.new(item),
        'ancestors': ActiveModel::Serializer::CollectionSerializer.new(item.ancestors, each_serializer: CpvSerializer)
      }, :callback => params[:callback]
    else
      render json: nil, :callback => params[:callback]
    end
  end

  # GET /api/v1/children
  # params: code
  def children
    parent = Cpv.where(code: params[:code]).first

    if parent.present?
      render json: {
        'cpvs': ActiveModel::Serializer::CollectionSerializer.new(parent.children.sorted, each_serializer: CpvSerializer),
        'ancestors': ActiveModel::Serializer::CollectionSerializer.new(parent.ancestors, each_serializer: CpvSerializer)
      }, :callback => params[:callback]
    else
      render json: [], each_serializer: CpvSerializer, :root => 'cpvs', :callback => params[:callback]
    end
  end

  # GET /api/v1/search
  # params: q
  def search
    results = Cpv.search(params[:q])

    if results.present?
      render json: {
        'cpvs': ActiveModel::Serializer::CollectionSerializer.new(results, each_serializer: CpvSerializer)
      }, :callback => params[:callback]
    else
      render json: [], each_serializer: CpvSerializer, :root => 'cpvs', :callback => params[:callback]
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  # GET /
  def index
    # get all parent codes
    @parent_codes = Cpv.parent_codes

  end

  # GET /download
  def download
    send_file 'data/cpv_2008.csv',
      :type => 'text/csv; header=present',
      :disposition => "attachment"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CPV Coding Test</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <header>
      <div class="logo"><%= link_to 'CPV Coding Test', root_path %></div>
      <div class="placeholder"></div>
      <div class="links">
        <%= link_to "Download Data", download_path %>
      </div>
    </header>

    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/root/index.html.erb
<% if @parent_codes.present? %>

  <p>
    This site provides the ability to view the European Union Common Procurement Vocabulary (CPV) codes and descriptions.
    This data comes from the <a href="http://cpv.data.ac.uk/scheme-CPV2008.html" target="_blank">CPV website</a>.
  </p>

  <div class="cpv_container">

    <div class="cpv_main_categories">
      <h1>CPV Categories</h1>

      <p>Click on a category to view all of its items or search for CPVs below.</p>

      <input type="text" name="q" id="q" placeholder="Search for CPV" />


      <ul class="cpv-parents">
        <% @parent_codes.each do |code| %>
          <li>
            <% if code.has_children? %>
              <a href="#" class="cpv-parent" data-code="<%= code.code %>" title="Click to view items in this category"><%= "#{code.description} (#{code.code})" %></a>
            <% else %>
              <%= "#{code.description} (#{code.code})" %>
            <% end %>
          </li>
        <% end %>
      </ul>

      <div class="cpv-search-results">
      </div>

    </div>

    <div class="cpv_children">
    </div>

  </div>
<% else %>

  <div class="no-data">
    Sorry, at this time there is no data on file. Have you run the rake task yet to load the database?
  </div>

<% end %>